name: Mi Primer Workflow

on:
   push:
     branches:
       -main

jobs:
  build:
    runs-on: ubuntu-latest
    steps :
      - name: Clonar el Repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: action/setup-node@v3
        with:
          node-version: '18'
      
      - name: Instalar Dependencias
        run: action/setup-node@v3
        
      - name: Ejecutar Pruebas
        run: npm test   
